+´ñ´pasd

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -22,6 +22,18 @@ jobs:
         run: |
           pwd
           ls -al
+
+      - name: Debugging SSH connection
+        env:
+          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
+          REMOTE_USER: ${{ secrets.REMOTE_USER }}
+        run: |
+          echo "REMOTE_HOST: $REMOTE_HOST"
+          echo "REMOTE_USER: $REMOTE_USER"
+          ssh-keyscan -H $REMOTE_HOST >> ~/.ssh/known_hosts || { echo 'ssh-keyscan failed' ; exit 1; }
+          cat ~/.ssh/known_hosts
+          ssh -vvv -p5983 $REMOTE_USER@$REMOTE_HOST 'echo "SSH connection successful"' || { echo 'SSH connection failed' ; exit 1; }
+
       - name: Deploy to Server
         env:
           REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
